Repository maximcaron57/popspells, pull requests merged in 2021-03, with the labels that each got.

#19 adds first version of circleci config
  .circleci/config.yml
Labels: devops, enhancement

#26 add synced dependency folder to main repo
  .vsconfig
  Packages/manifest.json
  Packages/packages-lock.json
Labels: devops, enhancement

#24 added initial developer console
  Assets/Core.meta
  Assets/Core/DevConsole.cs
  Assets/Core/DevConsole.cs.meta
  Assets/Input.meta
  Assets/Input/Controls.inputactions
  Assets/Input/Controls.inputactions.meta
  Assets/Scenes/SampleScene.unity
  Assets/Utilities.meta
  Assets/Utilities/DeveloperConsole.meta
  Assets/Utilities/DeveloperConsole/Commands.meta
  Assets/Utilities/DeveloperConsole/Commands/ConsoleCommand.cs
  Assets/Utilities/DeveloperConsole/Commands/ConsoleCommand.cs.meta
  Assets/Utilities/DeveloperConsole/Commands/IConsoleCommand.cs
  Assets/Utilities/DeveloperConsole/Commands/IConsoleCommand.cs.meta
  Assets/Utilities/DeveloperConsole/DeveloperConsole.cs
  Assets/Utilities/DeveloperConsole/DeveloperConsole.cs.meta
  Assets/Utilities/DeveloperConsole/DeveloperConsoleBehaviour.cs
  Assets/Utilities/DeveloperConsole/DeveloperConsoleBehaviour.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SceneTemplateSettings.json
Labels: c#, core, enhancement

#12 Basic input processing script to be extended
  Assets/Controls.cs
  Assets/Controls.cs.meta
Labels: core, enhancement, script

#33 adds test assemblies and bumps unity test tools version
  Assets/Tests.meta
  Assets/Tests/EditMode.meta
  Assets/Tests/EditMode/EditMode.asmdef
  Assets/Tests/EditMode/EditMode.asmdef.meta
  Assets/Tests/EditMode/NewTestScript.cs
  Assets/Tests/EditMode/NewTestScript.cs.meta
  Assets/Tests/PlayMode.meta
  Assets/Tests/PlayMode/NewTestScript.cs
  Assets/Tests/PlayMode/NewTestScript.cs.meta
  Assets/Tests/PlayMode/PlayMode.asmdef
  Assets/Tests/PlayMode/PlayMode.asmdef.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: c#, enhancement, script

#31 adds coffeegit and extenject to dependencies
  Packages/manifest.json
  Packages/packages-lock.json
Labels: c#, devops, enhancement, unity

#36 Fix for the gameci github action
  .github/workflows/main.yml
  .gitignore
  Assets/Tests.meta
  Assets/Tests/EditMode.meta
  Assets/Tests/EditMode/EditMode.asmdef
  Assets/Tests/EditMode/EditModeTests.asmdef
  Assets/Tests/EditMode/EditModeTests.asmdef.meta
  Assets/Tests/EditMode/NewTestScript.cs
  Assets/Tests/EditMode/SampleEditModeTest.cs
  Assets/Tests/EditMode/SampleEditModeTest.cs.meta
  Assets/Tests/PlayMode.meta
  Assets/Tests/PlayMode/NewTestScript.cs
  Assets/Tests/PlayMode/PlayMode.asmdef
  Assets/Tests/PlayMode/PlayModeTests.asmdef
  Assets/Tests/PlayMode/PlayModeTests.asmdef.meta
  Assets/Tests/PlayMode/SamplePlayModeTest.cs
  Assets/Tests/PlayMode/SamplePlayModeTest.cs.meta
Labels: bug, devops, github

#43 added main menu with working play & quit button, also added first sce…
  Assets/Core/DevConsole.cs
  Assets/Menu.meta
  Assets/Menu/MainMenu.cs
  Assets/Menu/MainMenu.cs.meta
  Assets/Menu/TextMenuGradient.asset
  Assets/Menu/TextMenuGradient.asset.meta
  Assets/Scenes/MenuScene.unity
  Assets/Scenes/MenuScene.unity.meta
  Assets/Utilities/DeveloperConsole/DeveloperConsoleBehaviour.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: c#, enhancement, ui

#45 Feature/add test assembly definition
  Assets/Controls.cs
  Assets/Core/DevConsole.cs
  Assets/Core/DeveloperConsoleInstaller.cs
  Assets/Editor.meta
  Assets/Editor/DeveloperConsoleTests.cs
  Assets/Editor/DeveloperConsoleTests.cs.meta
  Assets/Menu/MainMenu.cs
  Assets/Scenes/MenuScene.unity
  Assets/Scripts.meta
  Assets/Scripts/Core.meta
  Assets/Scripts/Core/DeveloperConsoleInstaller.cs
  Assets/Scripts/Core/DeveloperConsoleInstaller.cs.meta
  Assets/Scripts/DeveloperConsole.meta
  Assets/Scripts/DeveloperConsole/CommandAttribute.cs
  Assets/Scripts/DeveloperConsole/CommandAttribute.cs.meta
  Assets/Scripts/DeveloperConsole/CommandHandler.cs
  Assets/Scripts/DeveloperConsole/CommandHandler.cs.meta
  Assets/Scripts/DeveloperConsole/Commands.meta
  Assets/Scripts/DeveloperConsole/Commands/ConsoleCommandBase.cs
  Assets/Scripts/DeveloperConsole/Commands/ConsoleCommandBase.cs.meta
  Assets/Scripts/DeveloperConsole/Commands/IConsoleCommand.cs
  Assets/Scripts/DeveloperConsole/Commands/IConsoleCommand.cs.meta
  Assets/Scripts/DeveloperConsole/Commands/SayCommand.cs
  Assets/Scripts/DeveloperConsole/Commands/SayCommand.cs.meta
  Assets/Scripts/DeveloperConsole/Console.prefab
  Assets/Scripts/DeveloperConsole/Console.prefab.meta
  Assets/Scripts/DeveloperConsole/DeveloperConsoleBehaviour.cs
  Assets/Scripts/DeveloperConsole/DeveloperConsoleBehaviour.cs.meta
  Assets/Scripts/InputControllers.meta
  Assets/Scripts/InputControllers/Controls.cs
  Assets/Scripts/InputControllers/Controls.cs.meta
  Assets/Scripts/Menu.meta
  Assets/Scripts/Menu/MainMenu.cs
  Assets/Scripts/Menu/MainMenu.cs.meta
  Assets/Scripts/Menu/TextMenuGradient.asset
  Assets/Scripts/Menu/TextMenuGradient.asset.meta
  Assets/Tests/EditMode/SampleEditModeTest.cs
  Assets/Utilities/DeveloperConsole/Commands/IConsoleCommand.cs
  Assets/Utilities/DeveloperConsole/Console.prefab
  ProjectSettings/EditorBuildSettings.asset
Labels: c#, core, enhancement, testing
